services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: bookstore_services
    container_name: bookstore_services_app
    volumes:
      - ../:/var/bookstore-services
    networks:
      - bookstore_services
    ports:
      - "5000:5000"
    command: flask --app bookstore --debug run --no-debugger --no-reload --host=0.0.0.0
  db:
    image: postgres:11.6-alpine
    container_name: bookstore_services_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bookstore_services
    ports:
      - "5432:5432"


networks:
  bookstore_services:
    driver: bridge